### ISSUE TITLE
Semantical refactor suggestion

### ISSUE THREAD

**Issue by GaryHilares** [grazomarin/grade-calculator#2]
For some reason, weights and amount of dropped assignments are considered `Grade`s in the `Section` type comment. I would recommend changing the type of `weight` to `Number` (or renaming the `Grade` type to `Percentage`) and changing the type of `dropped` to `Natural`.

**Comment by grazomarin** [comment]
Hi, sorry for the late reply; I had a lot on my plate. I agree that changing the `Grade` data type to `Percentage` would provide more clarity. So, I did do that. I also fixed the typo of `dropped` being a `Grade` data type and changed it to `Natural`. But I will keep `weight` a `Natural` as university course syllabuses don't usually write weights in decimals. You don't see assignments having a weight of "11.7%".
